version: "3"
services: 
  listings-services:
    build: "./listings-services"
    depends_on: 
      - listings-services-db
    environment: 
      - DB_URI=mysql://root:password@listings-services-db/db?charset=UTF8
    ports: 
      - 7100:7100
    volumes: 
      - ./listings-services:/opt/app
  
  listings-services-db:
    environment: 
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    image: mysql:5.7.20
    ports: 
      - 0.0.0.0:7200:3306
    
  users-services:
    build: "./users-services"
    depends_on: 
      - users-services-db
    environment: 
      - DB_URI=mysql://root:password@users-services-db/db?charset=UTF8
    ports: 
      - 7101:7101
    volumes: 
      - ./users-services:/opt/app
  
  users-services-db:
    environment: 
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    image: mysql:5.7.20
    ports: 
      - 0.0.0.0:7201:3306